using System.Collections.Concurrent;

namespace CVIS.FunctionalTesting.Reporting;

/// <summary>
/// Records test lifecycle events from TearDown hooks.
///
/// SOURCE for: cpn-lifecycle-report.html (debug/diagnostic)
/// NOT the source for: cpn-report.html (authoritative)
///
/// The authoritative report is generated by CVIS.Playwright.Reporting.Tool
/// after dotnet test completes, by parsing TRX and NUnit XML output files.
/// </summary>
public static class TestLifecycleLog
{
    private static readonly ConcurrentBag<TestLifecycleEntry> _entries = new();

    public static void Record(TestLifecycleEntry entry)
    {
        if (entry is null) return;
        _entries.Add(entry);
    }

    public static IReadOnlyList<TestLifecycleEntry> GetAll() =>
        new List<TestLifecycleEntry>(_entries);

    public static void Clear()
    {
        while (_entries.TryTake(out _)) { }
    }
}

public sealed class TestLifecycleEntry
{
    public string TestName { get; set; } = string.Empty;
    public string FixtureClass { get; set; } = string.Empty;
    public string Outcome { get; set; } = string.Empty;
    public string? Message { get; set; }
    public string? StackTrace { get; set; }
    public long DurationMs { get; set; }
    public DateTime StartedAt { get; set; }
}
